In [1]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("original array:\n",arr)

original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [2]:
#returns every other rows
print("\nEvery other rows:\n",arr[0:3:2])


Every other rows:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [4]:
#return every other elements
arr=np.array([1,2,3,4,5,6,7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array:arr[::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:arr[::2]: [1 3 5 7]


In [9]:
#slicing array
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[:2,:3]
print("\narray with first 2 rows and 3 columns:\n",temp)


array with first 2 rows and 3 columns:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [10]:
#integer array 
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\n elements at indices(0,3),(1,2),(2,1),""(3,0):\n",temp)


 elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [11]:
#boolean array indexing
cond=arr>2
#cond is a boolean array
temp=arr[cond]
print("\nElements greater than 2:\n",temp)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [3]:
import numpy as np
#joining 2 array
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])
arr=np.concatenate([arr1,arr2])
print(arr)

[1 2 3 4 5 6]


In [5]:
#horizontal join 
arr3=np.hstack([arr1,arr2])
print(arr3)

[1 2 3 4 5 6]


In [6]:
#vertical join 
arr4=np.vstack([arr1,arr2])
print(arr4)

[[1 2 3]
 [4 5 6]]


In [7]:
#Depth join 
arr5=np.dstack([arr1,arr2])
print(arr5)


[[[1 4]
  [2 5]
  [3 6]]]


In [12]:
#splitting of array
arr=np.array([1,2,3,4,5,6])
arrb=np.array_split(arr,3)
print(arr)
print(arrb)
print(arrb[0])
print(arrb[1])
print(arrb[2])
    

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
